import {COLORS, FONTSIZE, BREAKPOINTS, BORDERRADIUS, FONTWEIGHT, LETTERSPACING, FONTFAMILY, LINEHEIGHT, HEADLINE, TEXT, SPACING} from "../tokens"

export const defaultTheme = {
    FONTSIZE,
    COLORS,
    BREAKPOINTS,
    BORDERRADIUS,
    FONTWEIGHT,
    LETTERSPACING,
    FONTFAMILY,
    LINEHEIGHT,
    HEADLINE,
    TEXT,
    SPACING
} as const;